---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: red
  namespace: flux-system
spec:
  image: docker.io/lukamit/red
  interval: 1m0s
  secretRef:
    name: dockerhub

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: red
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: red
  policy:
    semver:
      range: ^1.x-0

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: red
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: red
  policy:
    semver:
      range: ^1.x-0

